import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { GoogleOAuthProvider } from "@react-oauth/google";
import Navbar from "./components/Navbar";

import DarkVeil from '@/components/DarkVeil';
import DarkModeToggle
  from "./components/DarkModeToggle";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-black text-white`}
      >

        <div style={{ width: '100%', height: '600px', position: 'relative' }}>
          <DarkVeil
            hueShift={327}
            noiseIntensity={0}
            scanlineIntensity={0}
            speed={1.7}
            scanlineFrequency={2}
            warpAmount={0}
          />
          <GoogleOAuthProvider
          clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID!}
        >
          <Navbar />
          <div className="pt-24">{children}</div>
        </GoogleOAuthProvider>
        </div>
        
      </body>
    </html>
  );
}
